[package]
name = "ankurah-rn-bindings"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]
name = "ankurah_rn_bindings"

[dependencies]
uniffi = "0.29"

